Trainer.destroy_all
Team.destroy_all
Pokemon.destroy_all

chau = Trainer.create(name: "Pokemon Master Chau", username: "chautran", password: "password", wins: 999, losses: 0, bio: "I say you too when the waiter tells me to enjoy my food.")
jasper = Trainer.create(name: "Pokemon Master Jasper", username: "jasperreed", password: "password", wins: 999, losses: 0, bio: "Cupid shuffle!")

Team.create(name: "Chau's Team", trainer: chau, team: "magikarp, magikarp, magikarp, magikarp, magikarp, magikarp")
Team.create(name: "Jasper's Team", trainer: jasper, team: "pikachu, moltres, mewtwo, dragonite, zapdos, articuno")

Pokemon.create(name: "bulbasaur", types: "grass, poison", hp: 231, atk: 134, def: 134, sp_a: 166, sp_d: 166, spd: 126, moves: "leaf-storm, sludge-bomb, energy-ball, body-slam")
Pokemon.create(name: "ivysaur", types: "grass, poison", hp: 261, atk: 160, def: 162, sp_a: 196, sp_d: 196, spd: 156, moves: "leaf-storm, sludge-bomb, energy-ball, body-slam")
Pokemon.create(name: "venusaur", types: "grass, poison", hp: 301, atk: 200, def: 202, sp_a: 236, sp_d: 236, spd: 196, moves: "leaf-storm, sludge-bomb, energy-ball, earthquake")
Pokemon.create(name: "charmander", types: "fire", hp: 219, atk: 140, def: 122, sp_a: 156, sp_d: 136, spd: 166, moves: "fire-blast, shadow-claw, overheat, dragon-pulse")
Pokemon.create(name: "charmeleon", types: "fire", hp: 257, atk: 164, def: 152, sp_a: 196, sp_d: 166, spd: 196, moves: "fire-blast, shadow-claw, overheat, dragon-pulse")
Pokemon.create(name: "charizard", types: "fire", hp: 297, atk: 204, def: 192, sp_a: 254, sp_d: 206, spd: 236, moves: "scorching-sands, fire-blast, overheat, dragon-pulse")
Pokemon.create(name: "squirtle", types: "water", hp: 229, atk: 132, def: 166, sp_a: 136, sp_d: 164, spd: 122, moves: "hydro-pump, scald, dragon-pulse, aura-sphere")
Pokemon.create(name: "wartortle", types: "water", hp: 259, atk: 162, def: 196, sp_a: 166, sp_d: 196, spd: 152, moves: "hydro-pump, scald, dragon-pulse, aura-sphere")
Pokemon.create(name: "blastoise", types: "water", hp: 299, atk: 202, def: 236, sp_a: 206, sp_d: 246, spd: 192, moves: "hydro-pump, scald, dragon-pulse, aura-sphere")
Pokemon.create(name: "caterpie", types: "bug", hp: 231, atk: 96, def: 106, sp_a: 76, sp_d: 76, spd: 126, moves: "bug-bite, electroweb, tackle")
Pokemon.create(name: "metapod", types: "bug", hp: 241, atk: 76, def: 146, sp_a: 86, sp_d: 86, spd: 96, moves: "electroweb, harden")
Pokemon.create(name: "butterfree", types: "bug, flying", hp: 261, atk: 126, def: 136, sp_a: 216, sp_d: 296, spd: 176, moves: "pollen-puff, energy-ball, hurricane, shadow-ball")
Pokemon.create(name: "weedle", types: "bug, poison", hp: 221, atk: 106, def: 96, sp_a: 76, sp_d: 76, spd: 136, moves: "poison-sting")
Pokemon.create(name: "kakuna", types: "bug, poison", hp: 231, atk: 86, def: 136, sp_a: 86, sp_d: 86, spd: 106, moves: "harden")
Pokemon.create(name: "beedrill", types: "bug, poison", hp: 271, atk: 216, def: 116, sp_a: 126, sp_d: 196, spd: 186, moves: "drill-run, poison-jab, x-scissor, brick-break")
Pokemon.create(name: "pidgey", types: "normal, flying", hp: 221, atk: 126, def: 116, sp_a: 106, sp_d: 106, spd: 148, moves: "facade, u-turn, wing-attack, razor-wind")
Pokemon.create(name: "pidgeotto", types: "normal, flying", hp: 267, atk: 156, def: 146, sp_a: 136, sp_d: 136, spd: 178, moves: "facade, u-turn, wing-attack, razor-wind")
Pokemon.create(name: "pidgeot", types: "normal, flying", hp: 307, atk: 196, def: 186, sp_a: 176, sp_d: 176, spd: 238, moves: "facade, u-turn, wing-attack, sky-attack")
Pokemon.create(name: "rattata", types: "normal", hp: 201, atk: 148, def: 106, sp_a: 86, sp_d: 106, spd: 180, moves: "iron-tail, thunderbolt, shadow-ball, ice-beam")
Pokemon.create(name: "raticate", types: "normal", hp: 251, atk: 198, def: 156, sp_a: 136, sp_d: 176, spd: 230, moves: "hyper-fang, thunderbolt, shadow-ball, blizzard")
Pokemon.create(name: "spearow", types: "normal, flying", hp: 221, atk: 156, def: 96, sp_a: 98, sp_d: 98, spd: 176, moves: "drill-run, facade, u-turn, drill-peck")
Pokemon.create(name: "fearow", types: "normal, flying", hp: 271, atk: 216, def: 166, sp_a: 158, sp_d: 158, spd: 236, moves: "drill-run, facade, u-turn, drill-peck")
Pokemon.create(name: "ekans", types: "poison", hp: 211, atk: 156, def: 124, sp_a: 116, sp_d: 144, spd: 146, moves: "poison-jab, earthquake, iron-tail, facade")
Pokemon.create(name: "arbok", types: "poison", hp: 261, atk: 226, def: 174, sp_a: 166, sp_d: 194, spd: 196, moves: "poison-jab, earthquake, iron-tail, dragon-tail")
Pokemon.create(name: "pikachu", types: "electric", hp: 211, atk: 146, def: 116, sp_a: 136, sp_d: 136, spd: 216, moves: "play-rough, wild-charge, surf, brick-break")
Pokemon.create(name: "raichu", types: "electric", hp: 261, atk: 216, def: 146, sp_a: 216, sp_d: 196, spd: 256, moves: "play-rough, wild-charge, surf, brick-break")
Pokemon.create(name: "sandshrew", types: "ground", hp: 241, atk: 186, def: 206, sp_a: 76, sp_d: 96, spd: 116, moves: "shadow-claw, throat-chop, stomping-tantrum, poison-jab")
Pokemon.create(name: "sandslash", types: "ground", hp: 291, atk: 236, def: 256, sp_a: 126, sp_d: 146, spd: 166, moves: "shadow-claw, throat-chop, stomping-tantrum, poison-jab")
Pokemon.create(name: "nidoran-♀", types: "poison", hp: 251, atk: 130, def: 140, sp_a: 116, sp_d: 116, spd: 118, moves: "shadow-claw, facade, crunch, poison-jab")
Pokemon.create(name: "nidorina", types: "poison", hp: 281, atk: 160, def: 170, sp_a: 146, sp_d: 146, spd: 148, moves: "shadow-claw, facade, crunch, poison-jab")
Pokemon.create(name: "nidoqueen", types: "poison", hp: 321, atk: 220, def: 210, sp_a: 186, sp_d: 206, spd: 188, moves: "fire-punch, ice-punch, throat-chop, poison-jab")
Pokemon.create(name: "nidoran-♂", types: "poison", hp: 233, atk: 150, def: 116, sp_a: 116, sp_d: 116, spd: 136, moves: "shadow-claw, facade, drill-run, poison-jab")
Pokemon.create(name: "nidorino", types: "poison", hp: 263, atk: 180, def: 150, sp_a: 146, sp_d: 146, spd: 166, moves: "shadow-claw, facade, drill-run, poison-jab")
Pokemon.create(name: "nidoking", types: "poison", hp: 303, atk: 240, def: 190, sp_a: 206, sp_d: 186, spd: 206, moves: "fire-punch, ice-punch, megahorn, poison-jab")
Pokemon.create(name: "clefairy", types: "fairy", hp: 281, atk: 126, def: 132, sp_a: 156, sp_d: 166, spd: 106, moves: "misty-explosion, meteor-beam, mystical-fire, psychic")
Pokemon.create(name: "clefable", types: "fairy", hp: 331, atk: 176, def: 182, sp_a: 226, sp_d: 216, spd: 156, moves: "misty-explosion, meteor-beam, mystical-fire, psychic")
Pokemon.create(name: "vulpix", types: "fire", hp: 217, atk: 118, def: 116, sp_a: 136, sp_d: 166, spd: 166, moves: "dark-pulse, hex, overheat, energy-ball")
Pokemon.create(name: "ninetales", types: "fire", hp: 287, atk: 188, def: 186, sp_a: 198, sp_d: 236, spd: 236, moves: "dark-pulse, hex, overheat, energy-ball")
Pokemon.create(name: "jigglypuff", types: "normal, fairy", hp: 371, atk: 126, def: 76, sp_a: 126, sp_d: 86, spd: 76, moves: "dazzling-gleam, fire-blast, thunderbolt, ice-beam")
Pokemon.create(name: "wigglytuff", types: "normal, fairy", hp: 421, atk: 176, def: 126, sp_a: 206, sp_d: 136, spd: 126, moves: "dazzling-gleam, fire-blast, thunderbolt, ice-beam")
Pokemon.create(name: "zubat", types: "poison, flying", hp: 221, atk: 126, def: 106, sp_a: 96, sp_d: 116, spd: 146, moves: "zen-headbutt, u-turn, crunch, acrobatics")
Pokemon.create(name: "golbat", types: "poison, flying", hp: 291, atk: 196, def: 176, sp_a: 166, sp_d: 186, spd: 216, moves: "zen-headbutt, u-turn, crunch, acrobatics")
Pokemon.create(name: "oddish", types: "grass, poison", hp: 231, atk: 136, def: 146, sp_a: 186, sp_d: 166, spd: 96, moves: "dazzling-gleam, energy-ball, petal-dance, sludge-bomb")
Pokemon.create(name: "gloom", types: "grass, poison", hp: 261, atk: 166, def: 176, sp_a: 206, sp_d: 186, spd: 116, moves: "dazzling-gleam, energy-ball, petal-dance, sludge-bomb")
Pokemon.create(name: "vileplume", types: "grass, poison", hp: 291, atk: 196, def: 206, sp_a: 256, sp_d: 216, spd: 136, moves: "dazzling-gleam, energy-ball, petal-dance, sludge-bomb")
Pokemon.create(name: "paras", types: "bug, grass", hp: 211, atk: 176, def: 146, sp_a: 126, sp_d: 146, spd: 86, moves: "x-scissor, brick-break, facade, sludge-bomb")
Pokemon.create(name: "parasect", types: "bug, grass", hp: 261, atk: 226, def: 196, sp_a: 156, sp_d: 196, spd: 96, moves: "x-scissor, brick-break, facade, sludge-bomb")
Pokemon.create(name: "venonat", types: "bug, poison", hp: 261, atk: 146, def: 136, sp_a: 116, sp_d: 146, spd: 126, moves: "zen-headbutt, facade, psychic, sludge-bomb")
Pokemon.create(name: "venomoth", types: "bug, poison", hp: 281, atk: 166, def: 156, sp_a: 216, sp_d: 186, spd: 216, moves: "gust, bug-buzz, psychic, sludge-bomb")
Pokemon.create(name: "diglett", types: "ground", hp: 161, atk: 146, def: 86, sp_a: 106, sp_d: 126, spd: 226, moves: "earthquake, shadow-claw, slash, rock-slide")
Pokemon.create(name: "dugtrio", types: "ground", hp: 211, atk: 236, def: 136, sp_a: 136, sp_d: 176, spd: 276, moves: "earthquake, shadow-claw, slash, rock-slide")
Pokemon.create(name: "meowth", types: "normal", hp: 221, atk: 126, def: 106, sp_a: 116, sp_d: 116, spd: 216, moves: "shadow-claw, seed-bomb, play-rough, foul-play")
Pokemon.create(name: "persian", types: "normal", hp: 271, atk: 176, def: 156, sp_a: 166, sp_d: 166, spd: 266, moves: "shadow-claw, seed-bomb, play-rough, foul-play")
Pokemon.create(name: "psyduck", types: "water", hp: 241, atk: 140, def: 132, sp_a: 166, sp_d: 136, spd: 146, moves: "scald, future-sight, hydro-pump, ice-beam")
Pokemon.create(name: "golduck", types: "water", hp: 301, atk: 200, def: 192, sp_a: 226, sp_d: 196, spd: 206, moves: "scald, future-sight, hydro-pump, ice-beam")

puts "🌱🌱🌱  Bulbasaur used leech seed!  🌱🌱🌱"